### PR TITLE
Pick up http as endpoint when SRV starts with _http

### LINKED ISSUE #94: ServiceLocator is failing to add URI scheme when using `_http._tcp`
When looking for a service configured as:

```
-Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.my-service-ext.0=_http._tcp.my-service.test.svc.cluster.local
```

The returned URI does not contain the scheme (in such case `http`) and then, the URI is not valid for later usage.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #94

### CODE REVIEW

File: service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala [hunk 1]
```diff
@@ -219,6 +225,8 @@ trait ServiceLocatorLike {
       protocol
 
   private def doLookup(namespace: Option[String], name: String, endpoint: String, externalChecks: Int)(implicit as: ActorSystem): Future[Seq[Service]] = {
+    as.log.debug(s"looking up namespace = $namespace, name = $name, endpoint = $endpoint, externalChecks = $externalChecks")
```
Comment (marcospereira) [inline service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala]: 👍
